### ISSUE TITLE
Copy&paste typo in Types.Defaults

### ISSUE THREAD

**Issue by tbeu** [dzimmer/PlanarMechanics#104]
Comment of Types.Defaults reads `Default settings of the MultiBody library via constants`. I guess the lib name needs to be adpated.

**Comment by tobolar** [comment]
For the simplicity reasons, we can just delete "MultiBody" text from the description.

**Comment by tbeu** [comment]
Why not simply reuse existing constants?

**Comment by tobolar** [comment]
In Types.Defaults there are defined particularly colours and dimensions which are used for animation. In my opinion, it is better to have different values to easily distinguish between planar and 3D world. May be it is not a problem at the moment but would be more in focus as long as the planar-to-3D connection will be developed/improved in the future.
