### ISSUE TITLE
Speed present in package.order but non existent

### ISSUE THREAD

**Issue by adrpo** [dzimmer/PlanarMechanics#124]
This commit: https://github.com/dzimmer/PlanarMechanics/commit/2f605bc7b4aa3df724031f41487c95330cd34986
has added Speed in package.order but is not present in the package.mo or in that directory.
https://github.com/dzimmer/PlanarMechanics/commit/2f605bc7b4aa3df724031f41487c95330cd34986#diff-7a3eb6acb67aa007c262b34cfb2e93b2R4

**Comment by tobolar** [comment]
See also PR #126 for handling of directories `Translatonal` and `Rotational` added by mistake.
