### ISSUE TITLE
AbsoluteAcceleration resolved in Frame_a

### ISSUE THREAD

**Issue by olivleno** [dzimmer/PlanarMechanics#139]
In the AbsoluteAcceleration I figured that resolving in frame_a does not lead to the expected results. I had to add another transformAbsoluteVector to get proper results.

**Comment by tobolar** [comment]
@olivleno Can you provide a simple exmple?

**Comment by olivleno** [comment]
@tobolar thanks for taking a look at this. I reviewed you test case and it's fine. 
Yet, I have prepared an additional test case showing the problem. It's supposed to measure the centrifugal acceleration and is not leading to the results expected by myself. 
I have created a corresponding pull request. #
