### ISSUE TITLE
Simulation result baselines for correctness checking

### ISSUE THREAD

**Issue by maltelenz** [dzimmer/PlanarMechanics#144]
As a Modelica tool developer (in my case for Wolfram SystemModeler), it would be useful to have baselines that show the expected results for test and example models in third-party libraries (in this case PlanarMechanics), to ensure the tool is working correctly and is compatible with the library.

I can imagine it would be of interest to a library developer to aid in the library working correctly in as many tools as possible.

To that end, it would be useful if there were baselines, verified by the library developers, with the simulation behavior they expect from the library.
Is there interest in providing such baselines for the PlanarMechanics library?

One could look at the Modelica Standard Library for examples of how such baselines can be done. The central thing there are CSV files with a (manual) selection of variables and their values during a simulation for each simulation model (examples + test models).

**Comment by tobolar** [comment]
I only know results given in https://github.com/modelica/MAP-LIB_ReferenceResults. If this is what you address, how can we generate such references with a minimal effort?

**Comment by maltelenz** [comment]
That is exactly the kind of reference results I am talking about.

For the MSL results, there is this document that describes some of the creation process: https://trac.modelica.org/Modelica/raw-attachment/ticket/1392/SetupForMSLRegressionTesting_2014-01-13.pdf

I think it makes sense in general to follow the same patterns, allowing reuse of tooling. We would be happy with whatever you are willing to provide though.

The main parts needed from a tool developer perspective are:
* Which variables should be tested for each model
* Results for those variables in sufficiently high resolution, that have been verified by the library developer to be correct

**Comment by tobolar** [comment]
@dzimmer Where do we have to save such results? For Modelica Standard Library (https://github.com/modelica/ModelicaStandardLibrary), there is a particular repo https://github.com/modelica/MAP-LIB_ReferenceResults associated to the organization. I.e. the Library and ReferenceResults are saved separately. This would require something like https://github.com/dzimmer/PlanarMechanics_ReferenceResults/.

**Comment by tobolar** [comment]
@maltelenz I have prepared https://github.com/DLR-SR/PlanarMechanics_ReferenceResults. Please try if suitable for tool tests.

**Comment by maltelenz** [comment]
@tobolar This is great!
The format of the repository and files is exactly what we needed, and I was able to reuse our existing tooling from the MSL baselines.

I'm assuming the results were computed with the same tool as the library was developed? If so, that brings us at least part of the way towards "verified" results, since presumably the library developer(s) have run the models and checked results during development to some degree. Of course, an explicit manual correctness verification would be even better.

What version of the library was used for the results in the provided repository? From our perspective, if you could provide such results for the latest release (1.4.1), and new results for each new release you make, that would be perfect.

**Comment by tobolar** [comment]
@maltelenz 
> I'm assuming the results were computed with the same tool as the library was developed? If so, that brings us at least part of the way towards "verified" results, since presumably the library developer(s) have run the models and checked results during development to some degree. Of course, an explicit manual correctness verification would be even better.

Actually, Dymola 2020x ;-)  And I fully agree with you - even if not being able to express the issue so precisely.
To minimize necessary effort, I would only check the results if you or other tool vendors realize significant discrepancies in results. Which hopefully will not happen.

> What version of the library was used for the results in the provided repository? From our perspective, if you could provide such results for the latest release (1.4.1), and new results for each new release you make, that would be perfect.

How would you prefer to indicate the verison number? An additional info in "creation.txt"? And/or also in the directory name?

**Comment by tobolar** [comment]
> What version of the library was used for the results in the provided repository? From our perspective, if you could provide such results for the latest release (1.4.1), and new results for each new release you make, that would be perfect.

We can realize this by "Releases" of PlanarMechanics_ReferenceResults as well.

**Comment by maltelenz** [comment]
The https://github.com/modelica/MAP-LIB_ReferenceResults seems to have chosen to create a branch for each release, which seems reasonable to me. That way baselines can be corrected on the relevant branch if problems are found.

> To minimize necessary effort, I would only check the results if you or other tool vendors realize significant discrepancies in results. Which hopefully will not happen.

I agree this seems like a sensible middle ground.

**Comment by tobolar** [comment]
@maltelenz Thanks.
Closing this issue for now.
