### ISSUE TITLE
Simulation result baselines for correctness checking of 1.5.0

### ISSUE THREAD

**Issue by maltelenz** [dzimmer/PlanarMechanics#152]
I see there is a new [1.5.0 release](https://github.com/dzimmer/PlanarMechanics/releases/tag/v1.5.0) for the library.

I'm wondering if there are plans to create new reference results for this version in https://github.com/DLR-SR/PlanarMechanics_ReferenceResults as discussed in #144?

**Comment by tobolar** [comment]
Preparing the new release I also checked the simulation results. There is indeed no change in results regarding new release. So I spare the effort to generate and upload the reference results.

**Comment by maltelenz** [comment]
OK, thank you for that information!
