### ISSUE TITLE
Normalized versor of Prismatic Joint shouldn't be of type Distance

### ISSUE THREAD

**Issue by dariomangoni** [dzimmer/PlanarMechanics#156]
The parameter `e` of the `PlanarMechanics.Joints.Prismatic` component is declared to be of type `Distance`, that in turns embeds the range limitation of `min=0`; however, since `e=r/l` and assuming that `r` is a generic direction (i.e. not necessarily in the first quadrant) then I think that `e` should be of type Position as well.

**Comment by tobolar** [comment]
It even showes `e` being unitless unit vector. Considering `e=r/l` with both `r` and `l` being of unit meter, `e` must have no unit. This also corresponds to `r0 = e0*s` with `e0 = R*e`, where both `r0` and `s` (joint position, scalar) are of unit meter. Thus, both `e`and `e0` must be unitless real.
I will change the type of `e` corrspondingly.
