### ISSUE TITLE
Issue with line endings in reference text files

### ISSUE THREAD

**Issue by maltelenz** [dzimmer/PlanarMechanics#174]
When I check out the repository (master) on a Linux machine, git detects changes in line endings in all the `comparisonSignals.txt` as well as the `PlanarMechanics/Resources/ReferenceVariables/readme.txt` file.

I see there is a .gitattributes file in the repository. Maybe something like this needs to be run to align the gitattributes settings with the actual files?
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings

**Comment by tobolar** [comment]
Here you are: f25d86bb835e6d22f6b973fc1889625542036b70
Thanks a lot!

**Comment by maltelenz** [comment]
Can confirm I can now do a clone of `master` and get a clean `git status` on Linux. Thanks!
