### ISSUE TITLE
Incorrect link into MSL DoubleArrow image

### ISSUE THREAD

**Issue by maltelenz** [dzimmer/PlanarMechanics#185]
This doesn't exist in MSL 4.0.0 (which is what the library claims to use):

https://github.com/dzimmer/PlanarMechanics/blob/b5c229dbbcac31317d222ee53f89e5cfb4c1a0c9/PlanarMechanics/Visualizers/Advanced/DoubleArrow.mo#L111

There is an `Advanced` missing in the path:

https://github.com/modelica/ModelicaStandardLibrary/blob/v4.0.0/Modelica/Resources/Images/Mechanics/MultiBody/Visualizers/Advanced/DoubleArrow.png

**Comment by maltelenz** [comment]
Some projects are worried about licensing of outside contributions, so I have gotten into the bad habit of mostly creating issues. I'll keep a pull request in mind if I discover any more issues in the future :)

Thanks for the quick fix.

**Comment by tobolar** [comment]
> Some projects are worried about licensing of outside contributions

Ah, that's true. I always forget about it.
PR's are nice but not necessarilly needed. Simply do what is more comfortable for you. I'm happy of either.
