### ISSUE TITLE
For release v1.6.0 you seem to have tagged a commit that is not in the master 

### ISSUE THREAD

**Issue by adrpo** [dzimmer/PlanarMechanics#200]
I guess you need to tag a commit that is in one of the existing branches, not from a branch in a PR.

**Comment by adrpo** [comment]
Basically you deleted the branch that holds the commit of the release: https://github.com/dzimmer/PlanarMechanics/pull/199

**Comment by adrpo** [comment]
Seems it doesn't matter:
https://github.com/orgs/community/discussions/23918
Just our OpenModelica PackageManager index update script barfs on this if the release commit is not in a branch. I'll see if I can fix it. I'll close this now.

**Comment by tobolar** [comment]
Sorry, I was not aware of this. So I simple re-generated the release again, this time related to `master`.

**Comment by adrpo** [comment]
Thank you! This will fix the issue we have with updating our index for now but I will fix our script to handle this case as well as it seems to be common.

**Comment by tobolar** [comment]
> ... I will fix our script to handle this case as well...

This is fine. And I'm indeed convinced the assignment of the tag is clearer now.
