### ISSUE TITLE
Set gravity to zero and turn off animateGravity in SingleTrackWithEngine and TwoTrackWithDifferentialGear

### ISSUE THREAD

**Issue by johanrhodin** [dzimmer/PlanarMechanics#64]
The `animateGravity` arrow looks wrong. One would expect the arrow to point down into the ground. See attached screenshot.
![screen shot 2015-01-14 at 10 36 18 am](https://cloud.githubusercontent.com/assets/460369/5742621/32684b00-9bd9-11e4-966c-69f5fc8f9c2c.png)
The other examples in `PlanarMechanics.VehicleComponents.Examples` are using `PlanarWorld planarWorld(g = {0, 0})`

**Comment by fvanderlinden** [comment]
The gravity was accidentely turned on. It should have been disables. It is fixed with pull request #65
