### ISSUE TITLE
Compatibility with 1D elements

### ISSUE THREAD

**Issue by andreasheckmann** [dzimmer/PlanarMechanics#66]
The PlanarMechanics joint elements adapt the useFlange parameter option, known for 3D, in order to  e.g. attach a 1D translatoric damper to a 2D prismatic joint.  However, only one 1D flange is attached to the joint, which is different to the 3D Multibody library, where the 1D damper force is attached to both sides of the joint according to Newton's actio = reactio theorem.
Due to  equations in the 1D elements with flange_a and flange_b such as 
 s_rel = flange_b.s - flange_a.s;   v_rel = der(s_rel)
these 1D elements do not go together with the 2D joints.

**Comment by tobolar** [comment]
Actually, the 3D joints from Modelica.Mechanics.MultiBody.Joints (Prismatic o. Revolute) introduces a 'support' flange but it is internally connected to a 1D fixed component and not used anywhere. Therefore, it is not necessarilly needed to introduce support flange for 2D components. You can simply connect a fixed element to the 'free' flange of a 1D element connected with the other flange to 2D.  
But I agree it would be more convenient for the user to have such a support flange.

I suppose this only concerns the two models:
PlanarMechanics.Joints.Prismatic
PlanarMechanics.Joints.Revolute

**Comment by dzimmer** [comment]
Support flanges are now added.

**Comment by fvanderlinden** [comment]
We need a documentation for this, just adding them is "slightly" donfusing as the model does not say anything about it...

**Comment by tobolar** [comment]
Supplement to https://github.com/dzimmer/PlanarMechanics/issues/66#issuecomment-75808569: added in commit a19d67d92f8a215fd9125273a1dc2d4b21021380.
