### ISSUE TITLE
Bug with World and Gravity Animation

### ISSUE THREAD

**Issue by fvanderlinden** [dzimmer/PlanarMechanics#72]
2D World now pulls the 3D world after latest update, making it display the axis system, also when "no animation of gravity and "no gravity animation"

**Comment by dzimmer** [comment]
Now, there are two world models in order to solve this issue. The default planar world does not enable coupling to 3D. There is a second world model to do this.
If this is a permanent or temporary solution is not yet decided. Future will tell...
