### ISSUE TITLE
Missing 'color' parameter in some models from package Parts

### ISSUE THREAD

**Issue by tobolar** [dzimmer/PlanarMechanics#85]
Is there any reason why there is no parameter for color in some models from PlanarMechanics.Parts, e.g. Body or FixedTranslation? If not, I would add such parameter and 'linked' it to default colors as defined in PlanarMechanics.Types.Defaults.

**Comment by fvanderlinden** [comment]
The reason was that it is simply not done untill now :). Please feel free to add colors!

**Comment by tobolar** [comment]
Fixed in #86
