### ISSUE TITLE
Are BaseClasses missing?

### ISSUE THREAD

**Issue by tbeu** [dzimmer/PlanarMechanics#88]
BaseClasses are referenced but not within the library.

**Comment by adrpo** [comment]
Yes, it seems so, these models fail:
PlanarMechanics.Examples.PowerDistanceDemo
PlanarMechanics.Examples.SpringDamperDemo
PlanarMechanics.Examples.SpringDemo
because they reference non-existing:
BaseClasses.TwoConnectorShapes
