### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by annelim** [dzimmer/PlanarMechanics#94]
In the documentation for PlanarMechanics.GearComponents.RigidNoLossExternal and PlanarMechanics.GearComponents.RigidNoLossInternal, there are broken links to modelica://Actuator.Mechanical.Planar.Examples.SpurGear. The intention is probably to link to PlanarMechanics.GearComponents.Examples.SpurGear.

**Comment by fvanderlinden** [comment]
solved with #96
