### ISSUE TITLE
Broken image links into Modelica standard library

### ISSUE THREAD

**Issue by maltelenz** [dzimmer/PlanarMechanics#95]
There are two links from PlanarMechanics into the Modelica standard library Resources directory with incorrect paths.

`PlanarMechanics.Sensors.CutForceAndTorque`
links to
`modelica://Modelica/Resources/Images/MultiBody/Sensors/CutForceAndTorque.png`
but should probably link to
`modelica://Modelica/Resources/Images/Mechanics/MultiBody/Sensors/CutForceAndTorque.png`

`PlanarMechanics.Sensors.Distance`
links to
`modelica://Modelica/Resources/Images/MultiBody/Sensors/Distance.png`
but should probably link to
`modelica://Modelica/Resources/Images/Mechanics/MultiBody/Sensors/Distance.png`

**Comment by fvanderlinden** [comment]
Solved with #96
